### ISSUE TITLE
Multiple URI issues

### ISSUE THREAD

**Issue by kreuzerkrieg** [cpp-netlib/cpp-netlib#509]
I observe some strange behaviour when parsing invalid URLs
I'm trying to achieve the following, in case I get web escaped URL, try to validate it and if validation fails try to unescape it and re-validate.
As a result I get the following:
the URL, double escaped:
```
std::string url = "https:%252F%252Fwww.google.co.il%252F%253Fgfe_rd%253Dcr%"
                      "2526ei%253DI6AJVcX5IpPj8wfc8YDACA%2526gws_rd%253Dssl%"
                      "2523q%253Dhttp:%25252F%25252Fedition.cnn.com%25252F2015%"
                      "25252F03%25252F18%25252Fafrica%25252Ftunisia-parliament-"
                      "evacuated%25252Findex.html";
```
the code:
```
boost::network::uri::uri uri(url);
auto res = boost::network::uri::valid(uri); // for some reason returns true
auto host = boost::network::uri::host(uri); // fails with "incompatible iterators"
```

Am I doing something wrong? is it a bug?

P.S. using last stable source - 0.11.1

**Comment by deanberris** [comment]
Technically, it is a valid URI -- you have a protocol (stuff before the first ":"), then a user_info field (stuff before the second ":" and until the end of the string).

You technically have no host, which is why the parser is complaining.

What was your expectation? Technically we do not do scheme-specific parsing, i.e. do something magical that's only applicable to HTTP.

If you're only using the URI library, do you mind trying out the implementation that @glynos has in https://github.com/cpp-netlib/uri -- that's better maintained for that part, and the implementation in 0.11.1 is sadly lacking.

**Comment by kreuzerkrieg** [comment]
I guess URI composed of scheme and userinfo only is not valid URI according to RFC, am I wrong?
Parser - I expect the range to be valid and testable if it empty.
will try the glynos implementation

**Comment by deanberris** [comment]
mailto:user@example.com is a valid URI.
