### ISSUE TITLE
Is cpp-netlib aiming to be part of boost?

### ISSUE THREAD

**Issue by mysyljr** [cpp-netlib/cpp-netlib#559]
Is cpp-netlib aiming to be part of boost? I think this can be doable.

**Comment by deanberris** [comment]
Not anymore. But if you'd like to make that happen, I'd be happy to help. :)

**Comment by mysyljr** [comment]
Not anymore? There must have been stories. I just know how to use boost build. And if needed ,turn it to boost style like header only or add http2.0 standard. But I don't understand any policy things. I'm glad to know the difficuties in this area.

**Comment by deanberris** [comment]
Yes, there are stories. :) But I don't have time to share them. :(

The library used to be header-only, then because of the complications of template metaprogramming it got really hard to get contributors. Now that we've moved from header-only to non-header-only, we've got more contributors but now the Boost.Build system started getting in our way so we moved to CMake. The boost file hierarchy and namespace also gave us problems when trying to upgrade or integrate with non-Boost installations.

The next major version of the library will remove all traces of the Boost namespace, will use C++11 and/or C++14 exclusively, use Google's test framework, use CMake as a the build generator, and will have a non-header component by default. If you'd like to implement http/2 on top of the 0.11-devel branch that still has the Boost namespace and would like to try to get that into Boost, I'd be more than happy to review changes -- and ship them out too.

In the meantime, there's zero effort from me to try and get the library into Boost. If you'd like to take that on, I'd be very supportive of that effort. :)

**Comment by mysyljr** [comment]
I'll do it.

**Comment by deanberris** [comment]
Awesome, thanks @mysyljr -- let me know how I can help and when you get pull requests, please grab my attention too.

Cheers

**Comment by mysyljr** [comment]
Haha. I think the first step may be the most difficult part, because I didn't even use git and English well. But the code is one thing I can be sure of.

**Comment by deanberris** [comment]
@mysyljr -- any update on this?

**Comment by mysyljr** [comment]
It's a lightweight http2 implementation and I still can't integrate it into your lib. So the state is not good and has delayed for long.
