### ISSUE TITLE
Sync HTTP server ungracefully shuts down

### ISSUE THREAD

**Issue by banks** [cpp-netlib/cpp-netlib#562]
This is technically a feature request, however the comments in `sync_server_base::stop()` (https://github.com/cpp-netlib/cpp-netlib/blob/cpp-netlib-0.11.2-final/boost/network/protocol/http/server/sync_server.hpp#L52) seem to imply that graceful shutdown is intended already.

However the implementation simply stops acceptor (OK) and then stops entire IO service. Once IO service is stopped there is no chance of any callbacks on handlers continuing to process in-flight requests and all sockets are immediately closed implicitly. Assuming the primary use-case for sync server is a single threaded web server, it will just terminate here...

I can understand possibly not wanting to hard code a particular graceful shutdown routine here as there are many variables that might be required for people with different use cases, but in that case, it would be better to provide a public method to close `acceptor_` without terminating the entire io service abruptly. Right now `stop()` seems to be exactly equivalent to just calling `std::abort()` or leaving default signal handling which apparently makes it useless? I suppose if you did have some kind of global cleanup to perform it could be done after your call to `sync_server_base::run()` in which case stop would allow it to happen where abort wouldn't.

Did I miss something or is that comment misleading?

Thanks for the great lib!

**Comment by deanberris** [comment]
Sorry for the delay here @banks -- the short answer is, don't use the sync_server because it's deprecated. :)

The long answer is that it's really hard to ensure correct shutdown semantics in this case while guaranteeing that the destructor will not wait indefinitely. For that reason, we're encouraging everyone to just use the asynchronous server implementation which has better support for delayed shutdown semantics.
