### ISSUE TITLE
boost::network::http::client::request error when constructing with string

### ISSUE THREAD

**Issue by giacomodabisias** [cpp-netlib/cpp-netlib#564]
After quite some time I found this bug (?) or maybe its intended.
If I build a boost::network::http::client::request with a string like this

boost::network::http::client::request request(std::string("test"));

I get the following error

terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create

I had a look at the constructor of request and indeed it expects a constant reference.
request::request(std::string const& url)

Why is it implemented like this?

**Comment by mikhailberis** [comment]
> On 9 Oct 2015, at 12:15 AM, Giacomo Dabisias <notifications@github.com> wrote:
> 
> After quite some time I found this bug (?) or maybe its intended.
> If I build a boost::network::http::client::request with a string like this
> 
> boost::network::http::client::request request(std::string("test"));
> 
> I get the following error
> 
> terminate called after throwing an instance of 'std::length_error'
> what(): basic_string::_S_create
> 
> I had a look at the constructor of request and indeed it expects a constant reference.
> request::request(std::string const& url)
> 
> Why is it implemented like this? This way if I change at any point the passed url it won't work. It should make a copy of the url as is it passed or at some point during the construction.
> 
> 

This is implemented this way so that you can pass in a literal and it should just work.

The best way to do what you want I think is to create a request object, then use the destination modifier later on.

See http://cpp-netlib.org/0.11.2/reference/http_request.html#directives <http://cpp-netlib.org/0.11.2/reference/http_request.html#directives> for more details on how to use the destination directive or even the destination modifier.
