### ISSUE TITLE
Drop SSLv3 support from 0.11.2

### ISSUE THREAD

**Issue by infinity0** [cpp-netlib/cpp-netlib#570]
Hi, distros are starting to drop SSLv3 support in OpenSSL (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=768476#10) and this is causing rebuilds of cpp-netlib to break (see https://buildd.debian.org/status/package.php?p=cpp-netlib). Please drop SSLv3 support from cpp-netlib.

**Comment by deanberris** [comment]
Thanks @infinity0 -- do you have time to try this? I can work on this soonish, but it would have to be a 0.11.3 release that fixes it. Is that fine?

**Comment by infinity0** [comment]
Yes, a new release is fine. I don't think I have time to figure out the appropriate fix myself unfortunately.

**Comment by deanberris** [comment]
Okay, now that I've time to have a look, this seems to be an ASIO bug. Since Boost.Asio still allows users to do SSL v2/v3, it still has code that explicitly references some v3 symbols. I don't know whether Boost.Asio has fixed this yet, but I'd say in 1.59.0 it still uses v2/v3 (and somehow forces/requires it).

I'm not sure if there is a work-around on the cpp-netlib side, but I'm doing the next best thing which is to by default turn of v3 support. I will have a PR pending to do this.
