### ISSUE TITLE
Define http client connection buffer size

### ISSUE THREAD

**Issue by umennel** [cpp-netlib/cpp-netlib#842]
It is possible to define the server connection buffer size using BOOST_NETWORK_HTTP_SERVER_CONNECTION_BUFFER_SIZE. It is set to a default value if undefined. See [boost/network/protocol/http/server/async_connection.hpp](https://github.com/cpp-netlib/cpp-netlib/blob/0.13-release/boost/network/protocol/http/server/async_connection.hpp). Depending on the hardware, this may significantly increase data transfer rates, as shown in #726.
Could we have a similar macro for the client connection?

**Comment by deanberris** [comment]
Sounds like a good idea to me. I do think that since the client has options you can set to affect this already -- if not, then we should do both, controlling the size of the buffers from options and potentially changing the default for the option with a compile-time macro.

Do you mind sending a pull request to do that?

**Comment by umennel** [comment]
@deanberris, I didn't find a way to use the options because the buffer size is set at compile-time. See #843
