### ISSUE TITLE
Http library support

### ISSUE THREAD

**Issue by nginxsantos** [cpp-netlib/cpp-netlib#853]
Hi , I have few questions ?

- Does it suopport HTTP client functionality?
- Does it suuport HTTP2
- What is its threading model. Can it work as a library inside the application context?

**Comment by deanberris** [comment]
> Does it suopport HTTP client functionality?

Yes. See documentation for examples and reference.

> Does it suuport HTTP2

No. At least not yet, but pull requests towards adding support for HTTP2 would be welcome.

> What is its threading model. Can it work as a library inside the application context?

Not sure how to explain the threading model succinctly -- but it is thread-safe by design, and can be tuned to support multiple threads to handle network and protocol operations.

It is designed to work inside an application context (it is a C++ library after all).
